name: on-tag-do-release
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release -p:Version=${ steps.get_version.outputs.VERSION } --no-restore
      - name: Test
        run: dotnet test -c Release --no-restore --no-build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: nugets\*.nupkg
      - name: PushNuget
        run: dotnet nuget push nugets\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
